language: node_js
node_js: '8'

git:
  depth: 3

branches:
  only:
    - master
    - /^greenkeeper/.*$/

env:
  global:
    - NODE_ENV=test
    - PORT=3000

script: yarn test

after_success: yarn test:coverage
